name: Push Docker image to Registry

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Docker build & push      
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: https://registry.hub.docker.com/
          username: grolfskin
          password: tesFe001!!!!!!!

      - name: Increment Variable
        uses: action-pack/increment@v2
        with:
          name: 'MY_VARIABLE'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t registry.hub.docker.com/grolfskin/httpd:v${{ vars.MY_VARIABLE }} .

      - name: Push Docker image
        run: docker push registry.hub.docker.com/grolfskin/httpd:v${{ vars.MY_VARIABLE }}
