name: Push Docker image to Registry

on:
  push:
    branches:
      - main

env:
  VERSION: 1 

jobs:
  push_to_registry:
    name: Docker build & push      
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Extract Metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: https://registry.hub.docker.com/:httpd

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: https://registry.hub.docker.com/
          username: grolfskin
          password: tesFe001!!!!!!!

      - name: Build Docker image
        run: docker build -t registry.hub.docker.com/grolfskin/httpd:v$VERSION+1 .

      - name: Push Docker image
        run: docker push registry.hub.docker.com/grolfskin/httpd:v$VERSION+1
